# http请求 有2个部分组成

# 1 请求行（只有1行）: Request Method / 
# 2 请求头 Headers（可以有多行）【注在请求头的下面要换两行，因为要保留两个换行符】


# 3 请求体 Body


# GET实例：https://www.baidu.com/s?wd=沐枫
# GET /?wd=沐枫 HTTP/1.1
# Host: www.baidu.com


# POST文件上传实例：
POST /api/file HTTP/1.1
Host: study.duyiedu.com
Content-Type: multipart/form-data; boundary=aaa


--aaa
Content-Disposition: form-data; name="cover"; filename="./files/001.jpg"
Content-Type: image/jpeg

< ./files/001.jpg
--aaa--